### ISSUE TITLE
Shape mismatch when comparing slice of variable to constant (cylp 0.9.0b1, Python 3.7.1)

### ISSUE THREAD

**Issue by BenChampion** [coin-or/CyLP#75]
Using cylp 0.9.0b1, Python 3.7.1
Run the modelling example in the README (after changing print to a function for Python3)

```python
import numpy as np
from cylp.cy import CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPArray

s = CyClpSimplex()

# Add variables
x = s.addVariable('x', 3)
y = s.addVariable('y', 2)

# Create coefficients and bounds
A = np.matrix([[1., 2., 0],[1., 0, 1.]])
B = np.matrix([[1., 0, 0], [0, 0, 1.]])
D = np.matrix([[1., 2.],[0, 1]])
a = CyLPArray([5, 2.5])
b = CyLPArray([4.2, 3])
x_u= CyLPArray([2., 3.5])

# Add constraints
s += A * x <= a
s += 2 <= B * x + D * y <= b
s += y >= 0
s += 1.1 <= x[1:3] <= x_u # ******* error here

# Set the objective function
c = CyLPArray([1., -2., 3.])
s.objective = c * x + 2 * y.sum()

# Solve using primal Simplex
s.primal()
print(s.primalVariableSolution['x'])
```

```
Traceback (most recent call last):
  File "cylp_test.py", line 23, in <module>
    s += 1.1 <= x[1:3] <= x_u # ******* error here
  File "cylp\cy\CyClpSimplex.pyx", line 1285, in cylp.cy.CyClpSimplex.CyClpSimplex.__iadd__
  File "cylp\cy\CyClpSimplex.pyx", line 1298, in cylp.cy.CyClpSimplex.CyClpSimplex.addConstraint
  File "[...]\lib\site-packages\cylp\py\modeling\CyLPModel.py", line 1008, in addConstraint
    c = cons.evaluate(consName)
  File "[...]\lib\site-packages\cylp\py\modeling\CyLPModel.py", line 293, in evaluate
    cons.perform(token, left, right)
  File "[...]\lib\site-packages\cylp\py\modeling\CyLPModel.py", line 523, in perform
    var.parent.lower[var.indices] = bound
ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)
```

Modifying to the following works and gives the expected result:
```python
s += x[1:3] >= np.matrix([1.1]*2)
s += x[1:3] <= x_u
```

```
Clp0006I 0  Obj 1.1 Primal inf 2.8999998 (2) Dual inf 5.01e+10 (5) w.o. free dual inf (4)
Clp0006I 5  Obj 1.3
Clp0000I Optimal - objective value 1.3
[0.2 2.  1.1]
```

**Comment by tkralphs** [comment]
This was reported in #68 and should already be fixed by af1abbb773dc0315364c1046e46df26185c5d5c3, which hasn't made it into release yet.
