### ISSUE TITLE
Install cylp with pip fails with different erros in docker

### ISSUE THREAD

**Issue by paltaa** [coin-or/CyLP#92]
If i do a pip3 install cylp it fails with: 

```
    Converting to Python3 via 2to3...
    Warning: 'classifiers' should be a list, got type 'filter'
    Running from numpy source directory./tmp/pip-install-07mn95rn/numpy/build/py3k/numpy/distutils/misc_util.py:425: SyntaxWarning: "is" with a literal. Did you mean "=="?
      return is_string(s) and ('*' in s or '?' is s)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-07mn95rn/numpy/setup.py", line 211, in <module>
        setup_package()
      File "/tmp/pip-install-07mn95rn/numpy/setup.py", line 191, in setup_package
        setup(
      File "/tmp/pip-install-07mn95rn/numpy/build/py3k/numpy/distutils/core.py", line 152, in setup
        config = configuration()
      File "/tmp/pip-install-07mn95rn/numpy/setup.py", line 151, in configuration
        config.add_subpackage('numpy')
      File "/tmp/pip-install-07mn95rn/numpy/build/py3k/numpy/distutils/misc_util.py", line 970, in add_subpackage
        config_list = self.get_subpackage(subpackage_name,subpackage_path,
      File "/tmp/pip-install-07mn95rn/numpy/build/py3k/numpy/distutils/misc_util.py", line 936, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/tmp/pip-install-07mn95rn/numpy/build/py3k/numpy/distutils/misc_util.py", line 878, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "numpy/setup.py", line 5, in configuration
        config = Configuration('numpy',parent_package,top_path)
      File "/tmp/pip-install-07mn95rn/numpy/build/py3k/numpy/distutils/misc_util.py", line 713, in __init__
        raise ValueError("%r is not a directory" % (package_path,))
    ValueError: 'build/py3k/numpy' is not a directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

If i try to add it to requirements.txt and do a pip3 -r install requirements it fails with:

I've been trying to install CyLP from python3 docker image, Dockerfile:

```
FROM python:3

#EXPOSE 42400-42500

RUN mkdir -p /usr/src/metis

WORKDIR /usr/src/metis

RUN apt-get update

COPY requirements.txt .


# Install Cbc
RUN wget https://www.coin-or.org/download/source/Cbc/Cbc-2.9.9.tgz \
    && tar -xzf Cbc-2.9.9.tgz \
    && cd Cbc-2.9.9 \
    && ./configure --enable-cbc-parallel \
    && make \
    && make install \
    && rm -rf /usr/src/metis/Cbc-2.9.9.tgz

ENV COIN_INSTALL_DIR=/usr/src/metis/Cbc-2.9.9
ENV LD_LIBRARY_PATH=/usr/src/metis/Cbc-2.9.9/lib:$LD_LIBRARY_PATH

RUN pip3 install  -r requirements.txt --no-cache-dir

# Add GCC needed to compile CyLP
# RUN apt-get install python3-dev -y \
#     python-dev \
#     build-essential \
#     manpages-dev

# RUN gcc --version

# # Install CyLP

# COPY CyLP-py3 CyLP-py3

# WORKDIR  /usr/src/metis/CyLP-py3

# RUN COIN_INSTALL_DIR=/usr/src/metis/Cbc-2.9.9 python setup.py install 

WORKDIR /usr/src/metis/

COPY . .


RUN rm -rf /usr/src/metis/cylp-master.tar.gz
CMD [ "python3", "./main.py" ]
```
I even tried downloading and compiling it from source but still getting some errors, the error by trying to install in requirements.txt:

```
pika==1.1.0
numpy==1.17
scipy==1.4.1
cylp==0.9.3
```
Error:

```
Step 9/13 : RUN pip install  -r requirements.txt --no-cache-dir
 ---> Running in 101f73aa508a
Collecting pika==1.1.0
  Downloading pika-1.1.0-py2.py3-none-any.whl (148 kB)
Collecting numpy==1.17
  Downloading numpy-1.17.0.zip (6.5 MB)
Collecting scipy==1.4.1
  Downloading scipy-1.4.1-cp38-cp38-manylinux1_x86_64.whl (26.0 MB)
Collecting cylp==0.9.3
  Downloading cylp-0.9.3.tar.gz (1.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p8n5a_rr/cylp/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p8n5a_rr/cylp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-p8n5a_rr/cylp/pip-egg-info
         cwd: /tmp/pip-install-p8n5a_rr/cylp/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p8n5a_rr/cylp/setup.py", line 5, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by tkralphs** [comment]
There's a lot of weird stuff going on here and I can't really tell exactly what's going on from what you pasted in above. What instructions are you following? These are not the instructions from the most recent CyLP README. You should be using the latest release of Cbc stable/2.10 and ideally downloading and building with [coinbrew](https://github.com/coin-or/coinbrew). I also can't really tell what version of CyLP you're using, since you're copying in the source instead of just getting it from Pypi. 

In any case, there is already a container with CyLP pre-installed here: 

https://hub.docker.com/repository/docker/tkralphs/cylp

The Docker file is here:

https://github.com/tkralphs/cylp-docker/blob/master/image/Dockerfile

If you follow those instructions, it should work. If not, then please send the full output from building a container where everything is downloaded instead of copied so I can see exactly what's going on.

**Comment by paltaa** [comment]
@tkralphs Thanks a lot for the quick response! this was exactly what i was looking for, going to give it a try with the Dockerfile! Great! will get back to you

**Comment by tkralphs** [comment]
Actually, I realized that the Dockerfile needed to be updated, since CyLP no longer builds with the current master of Cbc. In case you tried and got a build failure, look at the latest commit that I just made to the [Dockerfile](https://github.com/tkralphs/cylp-docker/blob/master/image/Dockerfile). It is being test built at Dockerhub now.

**Comment by tkralphs** [comment]
Great!
